---
env_id: highway-v0
n_envs: &_n_envs 12
gamma: &_gamma 0.98
enable_venv_subprocess: &_enable_venv_subprocess True

env:
  observation:
    type: Kinematics
    features: &_observation_features
      [presence, x, y, vx, vy, cos_h, sin_h, heading]
    features_range:
      x: [0, 100]
      y: [0, 100]
      vx: [20, 30]
      vy: [0, 10]
    vehicles_count: 40
    order: sorted
    sea_behind: True
    # absolute: True
    normalize: True
  action:
    type: ContinuousAction
  duration: 300
  policy_frequency: 10
  simulation_frequency: 10
  vehicles_count: 100
  lanes_count: 6
  vehicles_density: 2
  offroad_terminal: True

PPO:
  model:
    policy: MlpPolicy
    policy_kwargs:
      net_arch: [{pi: [128, 128, 128, 128], vf: [128, 128, 128, 128]}]
    n_steps: 512
    batch_size: 64
    n_epochs: 10
    learning_rate: 0.0003
    gamma: *_gamma
    # tensorboard_log: tensorboard/MLP_relative
    verbose: 2
  train:
    total_timesteps: 1000000
    n_train_envs: *_n_envs
    n_eval_envs: *_n_envs
    eval_timesteps: 18000
    n_eval_episodes: *_n_envs
...